export const chapterEducationContent = {
  title: "Educación",
  subtitle: "Papeles del Real Arco",
  table: [
    { title: "Convertirse en masón del Real Arco", author: "" },
    { title: "Grados Capitulares de la Francmasonería", author: "" },
    { title: "Oficiales del Real Arco", author: "" },
    { title: "Más luz en el Real Arco", author: "" },
    { title: "Oficiales del Real Arco", author: "" },
    { title: "El Sicon Real Arco, rápido anular del viaje espiritual interior", author: "Comité de Educación Robert G. Davis" },
    { title: "El Símil Real Arco", author: "M.E. Steve Phillips, GJAC de Inglaterra, Gran Director de Ceremonias" },
    { title: "La misión del Real Arco", author: "W. Hno. Tsiniete Caf. C.R. Manassah, P.M." },
    { title: "La Necesidad del grado del Real Arco para el Maestro Masón", author: "" },
    { title: "Otras la masonería del Real Arco", author: "" },
    { title: "Hacia dónde está el Real Arco", author: "W. Hno. Gary Kerkin, PM Lodge Pakio No. 160" },
    { title: "Por qué amar el Real Arco?", author: "" },
    // Diccionario Masónico de los Caballeros del Norte
    { title: "Acos", author: "Edgar Fentum, PGHP" },
    { title: "Acos del Real Arco", author: "Charles E. Cathey, PGM Gran Logia de Carolina del Norte" },
    { title: "Estudiantes del Real Arco", author: "" },
    { title: "Realidad y Absoluto", author: "James Dearmore" },
    { title: "Primero Amos Reales y Sinodic Crípticos", author: "" },
    { title: "Santidad al Señor", author: "" },
    { title: "Sacra Real Arco de Jerusalén", author: "" },
    { title: "Jesús Zoroabel y Haggai", author: "" },
    { title: "Josué Zoroabel y Haggai", author: "" },
    { title: "Constructores de su Templo", author: "" },
    { title: "Vida religiosa", author: "" },
    { title: "Orígenes del Real Arco (Inglaterra)", author: "" },
    { title: "Parte de este Real Arco", author: "" },
    { title: "Real Arco Palabra Perdida", author: "" },
    { title: "Real Arco ?? Grado", author: "" },
    { title: "Zodiaco del Real Arco", author: "" },
    { title: "Tema de dedicación del Real Arco", author: "" },
    { title: "Terminos y definiciones del Real Arco", author: "" },
    { title: "Algunas mínimas esenciales del Real Arco", author: "" },
    { title: "Simbolismo, culto y realidad", author: "Edgar Fentum, PGHP" },
    { title: "La Palabra Perdida", author: "Hno. Arthur C. Parker, Nueva York" },
    { title: "La Palabra Masónica Inefable", author: "Diccionario Masónico de los Caballeros del Norte" },
    { title: "Las Conferencias del Sicon Real Arco", author: "" },
    { title: "El problema número 47 de Euclides", author: "" },
    { title: "El Roca del Sumo Sacerdote", author: "F. Graham Millar" },
    { title: "La Corona del Sumo Sacerdote", author: "Thomas C. Chavez, KYCH" },
    { title: "La destrucción y reconstrucción del templo del rey Salomón", author: "Edgar Fentum, PGHP" },
    { title: "La Palabra del Maestro", author: "Hno. S.W. Williams, Gran Sumo Sacerdote de Tennessee" },
    { title: "Los signos de las 12 tribus", author: "Por R.Ex. Comm. Roffe Jackel, PGJ, Gran Capítulo Lecturhttps://yorkriteca.org/NSW Comms" },
    { title: "El simbolismo de los colores", author: "" },
    { title: "El simbolismo del Real Arco", author: "" },
    { title: "El simbolismo de los velos", author: "" },
    { title: "La Triple y la Triple Tau", author: "H. Mej, HP, Toko Capítulo No.1 R.A.M." },
    { title: "El símbolo de la Triple y Triple Tau en la masonería del Real Arco", author: "H. Mej, HP, Toko Capítulo No.1 R.A.M." },
    { title: "La Triple Tau y la triquetra", author: "" },
    { title: "La Triple Tau en la masonería", author: "" },
    { title: "Los Rocos Tribu de Israel", author: "W. Hno. Tsiniete Caf. C.R. Manassah, P.M." },
    { title: "La señal del sacerdote", author: "" },
    { title: "Lo que atrae a tantos hermanos", author: "" },
    { title: "Adénse varas", author: "Edgar Fentum, PGHP" }
  ]
};